### ISSUE TITLE
Link to html version of the Modelica spec instead of pdf

### ISSUE THREAD

**Issue by bilderbuchi** [xogeny/ModelicaWebRef#25]
Instead of all the links in the pop-overs pointing to the spec pdf (where btw at least for me the intended hop-to-page is not working, as adobe reader is opened), it would be useful to link to an html version of the spec, e.g. [this one](http://modelica.readthedocs.org/en/latest/index.html), which looks official to me.
E.g. the link in the pop-over for `pre()`, which references section 3.7.3, but actually should reference 3.7.3.1 (where `pre`is defined), could link to the same section [here](http://modelica.readthedocs.org/en/latest/operators.html?highlight=pre#event-related-operators).

**Comment by xogeny** [comment]
Agreed.  However, the web reference was really just a stop gap until we had [my book](http://book.xogeny.com) online.  So I'm not really updating the web reference.

The page you linked to is not official (although some of us are pushing for a process that would allow an HTML version of the spec to be easily produced).

**Comment by bilderbuchi** [comment]
Alright, I can see that, although I found/find the webref pretty useful as a 1-page overview of the most important syntax elements.

Also, using the book instead would be fine, but it seems the search function is broken - I only [get](http://book.xogeny.com/search/?q=pre) "Preparing search / Searching...", but no results.

**Comment by bilderbuchi** [comment]
> it seems the search function is broken

I just found (xogeny/ModelicaBook#168) that this has been the case since 2014, so I posit that the web reference is still useful (and will probably remain so for a while still, considering that bug has been open for 2 years).
